In [97]:
import pandas as pd
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls
import numpy as np

import matplotlib.pyplot as plt

df = pd.read_excel("Python_variables(1).xlsx", \
                 header = 0)

df

,Month,nieuwe baan: (Nederland),CV,vacatures,uwv,uitkering,werkloos
0,2010-01,50,91,86,51,81,66
1,2010-02,54,100,89,55,83,57
2,2010-03,45,79,88,57,85,73
3,2010-04,53,68,81,50,75,45
4,2010-05,49,68,75,47,73,50
5,2010-06,52,76,79,52,70,55
6,2010-07,43,61,71,51,65,45
7,2010-08,63,65,80,50,70,51
8,2010-09,59,84,87,52,74,60
9,2010-10,68,79,80,50,72,52
10,2010-11,53,86,79,51,74,49
11,2010-12,52,58,63,49,68,47
12,2011-01,61,84,90,57,84,64
13,2011-02,73,91,87,57,79,63
14,2011-03,55,88,82,56,81,79
15,2011-04,56,64,77,50,70,65
16,2011-05,45,64,77,54,72,62
17,2011-06,58,64,74,51,67,58
18,2011-07,55,60,73,49,68,60
19,2011-08,61,57,82,50,70,53
20,2011-09,54,80,88,57,75,53
21,2011-10,55,72,85,56,74,77
22,2011-11,56,76,88,59,78,80
23,2011-12,55,54,73,55,76,72
24,2012-01,54,79,95,65,84,63
25,2012-02,56,95,92,62,80,77
26,2012-03,60,67,87,63,84,75
27,2012-04,44,61,83,59,73,73
28,2012-05,52,60,79,69,78,70
29,2012-06,57,55,80,61,71,60
...,...,...,...,...,...,...,...
48,2014-01,64,83,100,91,100,100
49,2014-02,66,91,92,90,94,96
50,2014-03,66,79,85,89,93,92
51,2014-04,58,68,83,82,85,83
52,2014-05,59,65,75,82,82,81
53,2014-06,73,60,74,78,78,77
54,2014-07,81,58,70,80,78,72
55,2014-08,67,56,75,74,74,67
56,2014-09,73,78,85,85,87,75
57,2014-10,65,73,82,80,88,74
58,2014-11,79,75,77,79,89,86
59,2014-12,67,55,67,81,87,70
60,2015-01,70,81,84,85,90,69
61,2015-02,69,89,84,91,87,75
62,2015-03,84,74,81,97,86,90
63,2015-04,69,68,72,83,80,76
64,2015-05,77,61,69,80,75,63
65,2015-06,85,63,71,84,84,72
66,2015-07,87,50,69,84,79,57
67,2015-08,70,55,74,81,76,56
68,2015-09,78,77,83,88,83,73
69,2015-10,70,74,77,81,82,77
70,2015-11,85,73,71,82,80,80
71,2015-12,81,58,61,96,82,75
72,2016-01,80,82,77,94,86,75
73,2016-02,100,84,77,100,89,75
74,2016-03,84,66,70,94,86,71
75,2016-04,92,69,66,89,79,68
76,2016-05,90,62,64,93,78,62
77,2016-06,90,62,63,81,73,50

In [98]:
df1 = pd.read_excel("Unemployment CBS(2).xlsx", \
                 header = 0)
df1

    werkloosheid  Unnamed: 1
0            5.4   65.853659
1            5.5   67.073171
2            5.4   65.853659
3            5.1   62.195122
4            5.0   60.975610
5            4.9   59.756098
6            4.7   57.317073
7            4.7   57.317073
8            4.9   59.756098
9            4.9   59.756098
10           4.9   59.756098
11           4.7   57.317073
12           5.2   63.414634
13           5.3   64.634146
14           5.1   62.195122
15           4.9   59.756098
16           4.8   58.536585
17           4.6   56.097561
18           4.6   56.097561
19           4.6   56.097561
20           5.1   62.195122
21           5.2   63.414634
22           5.4   65.853659
23           5.1   62.195122
24           5.8   70.731707
25           5.8   70.731707
26           5.8   70.731707
27           5.8   70.731707
28           5.6   68.292683
29           5.5   67.073171
..           ...         ...
48           8.1   98.780488
49           8.2  100.000000
50           8.1   98.780488
51           7.9   96.341463
52           7.5   91.463415
53           7.2   87.804878
54           7.0   85.365854
55           6.8   82.926829
56           7.1   86.585366
57           7.1   86.585366
58           7.1   86.585366
59           7.0   85.365854
60           7.6   92.682927
61           7.5   91.463415
62           7.3   89.024390
63           7.1   86.585366
64           6.9   84.146341
65           6.7   81.707317
66           6.5   79.268293
67           6.4   78.048780
68           6.8   82.926829
69           6.9   84.146341
70           6.6   80.487805
71           6.4   78.048780
72           6.8   82.926829
73           6.9   84.146341
74           6.7   81.707317
75           6.6   80.487805
76           6.2   75.609756
77           5.9   71.951220

[78 rows x 2 columns]

In [99]:

print(df1)

    werkloosheid  Unnamed: 1
0            5.4   65.853659
1            5.5   67.073171
2            5.4   65.853659
3            5.1   62.195122
4            5.0   60.975610
5            4.9   59.756098
6            4.7   57.317073
7            4.7   57.317073
8            4.9   59.756098
9            4.9   59.756098
10           4.9   59.756098
11           4.7   57.317073
12           5.2   63.414634
13           5.3   64.634146
14           5.1   62.195122
15           4.9   59.756098
16           4.8   58.536585
17           4.6   56.097561
18           4.6   56.097561
19           4.6   56.097561
20           5.1   62.195122
21           5.2   63.414634
22           5.4   65.853659
23           5.1   62.195122
24           5.8   70.731707
25           5.8   70.731707
26           5.8   70.731707
27           5.8   70.731707
28           5.6   68.292683
29           5.5   67.073171
..           ...         ...
48           8.1   98.780488
49           8.2  100.000000
50           8.1   98.780488
51           7.9   96.341463
52           7.5   91.463415
53           7.2   87.804878
54           7.0   85.365854
55           6.8   82.926829
56           7.1   86.585366
57           7.1   86.585366
58           7.1   86.585366
59           7.0   85.365854
60           7.6   92.682927
61           7.5   91.463415
62           7.3   89.024390
63           7.1   86.585366
64           6.9   84.146341
65           6.7   81.707317
66           6.5   79.268293
67           6.4   78.048780
68           6.8   82.926829
69           6.9   84.146341
70           6.6   80.487805
71           6.4   78.048780
72           6.8   82.926829
73           6.9   84.146341
74           6.7   81.707317
75           6.6   80.487805
76           6.2   75.609756
77           5.9   71.951220

[78 rows x 2 columns]

In [100]:
werkloosheid= df1.ix[:, 0]

In [101]:
werkloosheidindex = df1.ix[:,1]

In [102]:
print(werkloosheidindex)

0      65.853659
1      67.073171
2      65.853659
3      62.195122
4      60.975610
5      59.756098
6      57.317073
7      57.317073
8      59.756098
9      59.756098
10     59.756098
11     57.317073
12     63.414634
13     64.634146
14     62.195122
15     59.756098
16     58.536585
17     56.097561
18     56.097561
19     56.097561
20     62.195122
21     63.414634
22     65.853659
23     62.195122
24     70.731707
25     70.731707
26     70.731707
27     70.731707
28     68.292683
29     67.073171
         ...
48     98.780488
49    100.000000
50     98.780488
51     96.341463
52     91.463415
53     87.804878
54     85.365854
55     82.926829
56     86.585366
57     86.585366
58     86.585366
59     85.365854
60     92.682927
61     91.463415
62     89.024390
63     86.585366
64     84.146341
65     81.707317
66     79.268293
67     78.048780
68     82.926829
69     84.146341
70     80.487805
71     78.048780
72     82.926829
73     84.146341
74     81.707317
75     80.487805
76     75.609756
77     71.951220
Name: Unnamed: 1, dtype: float64

In [103]:
nieuwebaan = df.ix[:,1]
CV = df.ix[:,2]
vacatures = df.ix[:,3]
uwv = df.ix[:,4]
uitkering = df.ix[:,5] 
werkloos =  df.ix[:,6]

In [104]:
print(uitkering)

0      81
1      83
2      85
3      75
4      73
5      70
6      65
7      70
8      74
9      72
10     74
11     68
12     84
13     79
14     81
15     70
16     72
17     67
18     68
19     70
20     75
21     74
22     78
23     76
24     84
25     80
26     84
27     73
28     78
29     71
     ...
48    100
49     94
50     93
51     85
52     82
53     78
54     78
55     74
56     87
57     88
58     89
59     87
60     90
61     87
62     86
63     80
64     75
65     84
66     79
67     76
68     83
69     82
70     80
71     82
72     86
73     89
74     86
75     79
76     78
77     73
Name: uitkering, dtype: int64

In [136]:
trace = Scatter(y=werkloosheid, mode= 'lines', name = 'lines')
py.iplot([trace], filename='plot')

In [106]:
trace0 = Scatter(y=werkloosheidindex, mode= 'lines', name = 'werkloosheidindex')
trace1 = Scatter(y=nieuwebaan, mode= 'lines', name = 'nieuwe baan')
trace2 = Scatter(y=CV, mode= 'lines', name = 'CV')
trace3 = Scatter(y=vacatures, mode= 'lines', name = 'vacatures')
trace4 = Scatter(y=uwv, mode= 'lines', name = 'uwv')
trace5 = Scatter(y=uitkering, mode= 'lines', name = 'uitkering')
trace6 = Scatter(y=werkloos, mode= 'lines', name = 'werkloos')
data= [trace0, trace1, trace2, trace3, trace4, trace5, trace6]
py.iplot(data, filename='Plot2')

In [107]:
data1= [trace0, trace1]
py.iplot(data1, filename='Plot3')

In [108]:
df['Mean']=df.mean(axis=1)

In [109]:
print(df)

      Month  nieuwe baan: (Nederland)   CV  vacatures  uwv  uitkering  \
0   2010-01                        50   91         86   51         81
1   2010-02                        54  100         89   55         83
2   2010-03                        45   79         88   57         85
3   2010-04                        53   68         81   50         75
4   2010-05                        49   68         75   47         73
5   2010-06                        52   76         79   52         70
6   2010-07                        43   61         71   51         65
7   2010-08                        63   65         80   50         70
8   2010-09                        59   84         87   52         74
9   2010-10                        68   79         80   50         72
10  2010-11                        53   86         79   51         74
11  2010-12                        52   58         63   49         68
12  2011-01                        61   84         90   57         84
13  2011-02                        73   91         87   57         79
14  2011-03                        55   88         82   56         81
15  2011-04                        56   64         77   50         70
16  2011-05                        45   64         77   54         72
17  2011-06                        58   64         74   51         67
18  2011-07                        55   60         73   49         68
19  2011-08                        61   57         82   50         70
20  2011-09                        54   80         88   57         75
21  2011-10                        55   72         85   56         74
22  2011-11                        56   76         88   59         78
23  2011-12                        55   54         73   55         76
24  2012-01                        54   79         95   65         84
25  2012-02                        56   95         92   62         80
26  2012-03                        60   67         87   63         84
27  2012-04                        44   61         83   59         73
28  2012-05                        52   60         79   69         78
29  2012-06                        57   55         80   61         71
..      ...                       ...  ...        ...  ...        ...
48  2014-01                        64   83        100   91        100
49  2014-02                        66   91         92   90         94
50  2014-03                        66   79         85   89         93
51  2014-04                        58   68         83   82         85
52  2014-05                        59   65         75   82         82
53  2014-06                        73   60         74   78         78
54  2014-07                        81   58         70   80         78
55  2014-08                        67   56         75   74         74
56  2014-09                        73   78         85   85         87
57  2014-10                        65   73         82   80         88
58  2014-11                        79   75         77   79         89
59  2014-12                        67   55         67   81         87
60  2015-01                        70   81         84   85         90
61  2015-02                        69   89         84   91         87
62  2015-03                        84   74         81   97         86
63  2015-04                        69   68         72   83         80
64  2015-05                        77   61         69   80         75
65  2015-06                        85   63         71   84         84
66  2015-07                        87   50         69   84         79
67  2015-08                        70   55         74   81         76
68  2015-09                        78   77         83   88         83
69  2015-10                        70   74         77   81         82
70  2015-11                        85   73         71   82         80
71  2015-12                        81   58         61   96         82
72  2016-01                        80   82         77   94         86
73  2016-02                       100   84         77  100         89
74  2016-03                        84   66         70   94         86
75  2016-04                        92   69         66   89         79
76  2016-05                        90   62         64   93         78
77  2016-06                        90   62         63   81         73

    werkloos       Mean
0         66  70.833333
1         57  73.000000
2         73  71.166667
3         45  62.000000
4         50  60.333333
5         55  64.000000
6         45  56.000000
7         51  63.166667
8         60  69.333333
9         52  66.833333
10        49  65.333333
11        47  56.166667
12        64  73.333333
13        63  75.000000
14        79  73.500000
15        65  63.666667
16        62  62.333333
17        58  62.000000
18        60  60.833333
19        53  62.166667
20        53  67.833333
21        77  69.833333
22        80  72.833333
23        72  64.166667
24        63  73.333333
25        77  77.000000
26        75  72.666667
27        73  65.500000
28        70  68.000000
29        60  64.000000
..       ...        ...
48       100  89.666667
49        96  88.166667
50        92  84.000000
51        83  76.500000
52        81  74.000000
53        77  73.333333
54        72  73.166667
55        67  68.833333
56        75  80.500000
57        74  77.000000
58        86  80.833333
59        70  71.166667
60        69  79.833333
61        75  82.500000
62        90  85.333333
63        76  74.666667
64        63  70.833333
65        72  76.500000
66        57  71.000000
67        56  68.666667
68        73  80.333333
69        77  76.833333
70        80  78.500000
71        75  75.500000
72        75  82.333333
73        75  87.500000
74        71  78.500000
75        68  77.166667
76        62  74.833333
77        50  69.833333

[78 rows x 8 columns]

In [110]:
#Vanaf hier moeten we goed kijken of de data klopt. dec 2015 toch terug naar 58
index =  df.ix[:,7]
trace7 = Scatter(y=index, mode= 'lines', name = 'index')
data3= [trace6, trace7]
py.iplot(data3, filename='Plot3')

In [111]:
df3 = pd.concat([df, percentage], axis=1)

In [112]:
df4= pd.concat([df3, werkloosheid], axis=1)
print(df4)

      Month  nieuwe baan: (Nederland)   CV  vacatures  uwv  uitkering  \
0   2010-01                        50   91         86   51         81
1   2010-02                        54  100         89   55         83
2   2010-03                        45   79         88   57         85
3   2010-04                        53   68         81   50         75
4   2010-05                        49   68         75   47         73
5   2010-06                        52   76         79   52         70
6   2010-07                        43   61         71   51         65
7   2010-08                        63   65         80   50         70
8   2010-09                        59   84         87   52         74
9   2010-10                        68   79         80   50         72
10  2010-11                        53   86         79   51         74
11  2010-12                        52   58         63   49         68
12  2011-01                        61   84         90   57         84
13  2011-02                        73   91         87   57         79
14  2011-03                        55   88         82   56         81
15  2011-04                        56   64         77   50         70
16  2011-05                        45   64         77   54         72
17  2011-06                        58   64         74   51         67
18  2011-07                        55   60         73   49         68
19  2011-08                        61   57         82   50         70
20  2011-09                        54   80         88   57         75
21  2011-10                        55   72         85   56         74
22  2011-11                        56   76         88   59         78
23  2011-12                        55   54         73   55         76
24  2012-01                        54   79         95   65         84
25  2012-02                        56   95         92   62         80
26  2012-03                        60   67         87   63         84
27  2012-04                        44   61         83   59         73
28  2012-05                        52   60         79   69         78
29  2012-06                        57   55         80   61         71
..      ...                       ...  ...        ...  ...        ...
48  2014-01                        64   83        100   91        100
49  2014-02                        66   91         92   90         94
50  2014-03                        66   79         85   89         93
51  2014-04                        58   68         83   82         85
52  2014-05                        59   65         75   82         82
53  2014-06                        73   60         74   78         78
54  2014-07                        81   58         70   80         78
55  2014-08                        67   56         75   74         74
56  2014-09                        73   78         85   85         87
57  2014-10                        65   73         82   80         88
58  2014-11                        79   75         77   79         89
59  2014-12                        67   55         67   81         87
60  2015-01                        70   81         84   85         90
61  2015-02                        69   89         84   91         87
62  2015-03                        84   74         81   97         86
63  2015-04                        69   68         72   83         80
64  2015-05                        77   61         69   80         75
65  2015-06                        85   63         71   84         84
66  2015-07                        87   50         69   84         79
67  2015-08                        70   55         74   81         76
68  2015-09                        78   77         83   88         83
69  2015-10                        70   74         77   81         82
70  2015-11                        85   73         71   82         80
71  2015-12                        81   58         61   96         82
72  2016-01                        80   82         77   94         86
73  2016-02                       100   84         77  100         89
74  2016-03                        84   66         70   94         86
75  2016-04                        92   69         66   89         79
76  2016-05                        90   62         64   93         78
77  2016-06                        90   62         63   81         73

    werkloos       Mean  percentage  werkloosheid
0         66  70.833333   64.556962           5.4
1         57  73.000000   64.556962           5.5
2         73  71.166667   64.556962           5.4
3         45  62.000000   63.291139           5.1
4         50  60.333333   63.291139           5.0
5         55  64.000000   63.291139           4.9
6         45  56.000000   63.291139           4.7
7         51  63.166667   63.291139           4.7
8         60  69.333333   63.291139           4.9
9         52  66.833333   62.025316           4.9
10        49  65.333333   62.025316           4.9
11        47  56.166667   63.291139           4.7
12        64  73.333333   62.025316           5.2
13        63  75.000000   62.025316           5.3
14        79  73.500000   60.759494           5.1
15        65  63.666667   59.493671           4.9
16        62  62.333333   60.759494           4.8
17        58  62.000000   59.493671           4.6
18        60  60.833333   62.025316           4.6
19        53  62.166667   62.025316           4.6
20        53  67.833333   64.556962           5.1
21        77  69.833333   65.822785           5.2
22        80  72.833333   68.354430           5.4
23        72  64.166667   68.354430           5.1
24        63  73.333333   69.620253           5.8
25        77  77.000000   69.620253           5.8
26        75  72.666667   69.620253           5.8
27        73  65.500000   72.151899           5.8
28        70  68.000000   72.151899           5.6
29        60  64.000000   72.151899           5.5
..       ...        ...         ...           ...
48       100  89.666667   98.734177           8.1
49        96  88.166667  100.000000           8.2
50        92  84.000000   98.734177           8.1
51        83  76.500000   97.468354           7.9
52        81  74.000000   96.202532           7.5
53        77  73.333333   93.670886           7.2
54        72  73.166667   92.405063           7.0
55        67  68.833333   91.139241           6.8
56        75  80.500000   89.873418           7.1
57        74  77.000000   89.873418           7.1
58        86  80.833333   89.873418           7.1
59        70  71.166667   91.139241           7.0
60        69  79.833333   91.139241           7.6
61        75  82.500000   89.873418           7.5
62        90  85.333333   88.607595           7.3
63        76  74.666667   88.607595           7.1
64        63  70.833333   87.341772           6.9
65        72  76.500000   87.341772           6.7
66        57  71.000000   86.075949           6.5
67        56  68.666667   86.075949           6.4
68        73  80.333333   86.075949           6.8
69        77  76.833333   87.341772           6.9
70        80  78.500000   84.810127           6.6
71        75  75.500000   83.544304           6.4
72        75  82.333333   82.278481           6.8
73        75  87.500000   82.278481           6.9
74        71  78.500000   81.012658           6.7
75        68  77.166667   81.012658           6.6
76        62  74.833333   79.746835           6.2
77        50  69.833333   77.215190           5.9

[78 rows x 10 columns]

In [113]:
import statsmodels.formula.api as smf
lm = smf.ols(formula='werkloosheid ~ uitkering + CV + werkloos + uwv + nieuwebaan + vacatures', data=df3).fit()
lm.params

Intercept     0.741490
uitkering     0.018312
CV           -0.002288
werkloos      0.019899
uwv           0.043214
nieuwebaan   -0.004556
vacatures    -0.001014
dtype: float64

In [114]:
X_new = pd.DataFrame({'uitkering': [56],'CV': [93],'werkloos':[59],'uwv':[51],'nieuwebaan': [56],'vacatures': [87]})
X_new.head()

   CV  nieuwebaan  uitkering  uwv  vacatures  werkloos
0  93          56         56   51         87        59

In [115]:
preds = lm.predict(X_new)
preds

array([ 4.58883755])

In [116]:
lm1 = smf.ols(formula='werkloosheid ~ werkloos + uwv ', data=df3).fit()
lm1.params

Intercept    1.181898
werkloos     0.026708
uwv          0.043615
dtype: float64

In [117]:
X_new = pd.DataFrame({'werkloos': [59],'uwv': [51]})
X_new.head()

   uwv  werkloos
0   51        59

In [118]:
preds = lm1.predict(X_new)
preds

array([ 4.9820557])

In [119]:
X_new = pd.DataFrame({'werkloos': [67],'uwv': [85]})
X_new.head()

   uwv  werkloos
0   85        67

In [120]:
preds = lm1.predict(X_new)
preds

array([ 6.67863027])

In [121]:
print(df4)

      Month  nieuwe baan: (Nederland)   CV  vacatures  uwv  uitkering  \
0   2010-01                        50   91         86   51         81
1   2010-02                        54  100         89   55         83
2   2010-03                        45   79         88   57         85
3   2010-04                        53   68         81   50         75
4   2010-05                        49   68         75   47         73
5   2010-06                        52   76         79   52         70
6   2010-07                        43   61         71   51         65
7   2010-08                        63   65         80   50         70
8   2010-09                        59   84         87   52         74
9   2010-10                        68   79         80   50         72
10  2010-11                        53   86         79   51         74
11  2010-12                        52   58         63   49         68
12  2011-01                        61   84         90   57         84
13  2011-02                        73   91         87   57         79
14  2011-03                        55   88         82   56         81
15  2011-04                        56   64         77   50         70
16  2011-05                        45   64         77   54         72
17  2011-06                        58   64         74   51         67
18  2011-07                        55   60         73   49         68
19  2011-08                        61   57         82   50         70
20  2011-09                        54   80         88   57         75
21  2011-10                        55   72         85   56         74
22  2011-11                        56   76         88   59         78
23  2011-12                        55   54         73   55         76
24  2012-01                        54   79         95   65         84
25  2012-02                        56   95         92   62         80
26  2012-03                        60   67         87   63         84
27  2012-04                        44   61         83   59         73
28  2012-05                        52   60         79   69         78
29  2012-06                        57   55         80   61         71
..      ...                       ...  ...        ...  ...        ...
48  2014-01                        64   83        100   91        100
49  2014-02                        66   91         92   90         94
50  2014-03                        66   79         85   89         93
51  2014-04                        58   68         83   82         85
52  2014-05                        59   65         75   82         82
53  2014-06                        73   60         74   78         78
54  2014-07                        81   58         70   80         78
55  2014-08                        67   56         75   74         74
56  2014-09                        73   78         85   85         87
57  2014-10                        65   73         82   80         88
58  2014-11                        79   75         77   79         89
59  2014-12                        67   55         67   81         87
60  2015-01                        70   81         84   85         90
61  2015-02                        69   89         84   91         87
62  2015-03                        84   74         81   97         86
63  2015-04                        69   68         72   83         80
64  2015-05                        77   61         69   80         75
65  2015-06                        85   63         71   84         84
66  2015-07                        87   50         69   84         79
67  2015-08                        70   55         74   81         76
68  2015-09                        78   77         83   88         83
69  2015-10                        70   74         77   81         82
70  2015-11                        85   73         71   82         80
71  2015-12                        81   58         61   96         82
72  2016-01                        80   82         77   94         86
73  2016-02                       100   84         77  100         89
74  2016-03                        84   66         70   94         86
75  2016-04                        92   69         66   89         79
76  2016-05                        90   62         64   93         78
77  2016-06                        90   62         63   81         73

    werkloos       Mean  percentage  werkloosheid
0         66  70.833333   64.556962           5.4
1         57  73.000000   64.556962           5.5
2         73  71.166667   64.556962           5.4
3         45  62.000000   63.291139           5.1
4         50  60.333333   63.291139           5.0
5         55  64.000000   63.291139           4.9
6         45  56.000000   63.291139           4.7
7         51  63.166667   63.291139           4.7
8         60  69.333333   63.291139           4.9
9         52  66.833333   62.025316           4.9
10        49  65.333333   62.025316           4.9
11        47  56.166667   63.291139           4.7
12        64  73.333333   62.025316           5.2
13        63  75.000000   62.025316           5.3
14        79  73.500000   60.759494           5.1
15        65  63.666667   59.493671           4.9
16        62  62.333333   60.759494           4.8
17        58  62.000000   59.493671           4.6
18        60  60.833333   62.025316           4.6
19        53  62.166667   62.025316           4.6
20        53  67.833333   64.556962           5.1
21        77  69.833333   65.822785           5.2
22        80  72.833333   68.354430           5.4
23        72  64.166667   68.354430           5.1
24        63  73.333333   69.620253           5.8
25        77  77.000000   69.620253           5.8
26        75  72.666667   69.620253           5.8
27        73  65.500000   72.151899           5.8
28        70  68.000000   72.151899           5.6
29        60  64.000000   72.151899           5.5
..       ...        ...         ...           ...
48       100  89.666667   98.734177           8.1
49        96  88.166667  100.000000           8.2
50        92  84.000000   98.734177           8.1
51        83  76.500000   97.468354           7.9
52        81  74.000000   96.202532           7.5
53        77  73.333333   93.670886           7.2
54        72  73.166667   92.405063           7.0
55        67  68.833333   91.139241           6.8
56        75  80.500000   89.873418           7.1
57        74  77.000000   89.873418           7.1
58        86  80.833333   89.873418           7.1
59        70  71.166667   91.139241           7.0
60        69  79.833333   91.139241           7.6
61        75  82.500000   89.873418           7.5
62        90  85.333333   88.607595           7.3
63        76  74.666667   88.607595           7.1
64        63  70.833333   87.341772           6.9
65        72  76.500000   87.341772           6.7
66        57  71.000000   86.075949           6.5
67        56  68.666667   86.075949           6.4
68        73  80.333333   86.075949           6.8
69        77  76.833333   87.341772           6.9
70        80  78.500000   84.810127           6.6
71        75  75.500000   83.544304           6.4
72        75  82.333333   82.278481           6.8
73        75  87.500000   82.278481           6.9
74        71  78.500000   81.012658           6.7
75        68  77.166667   81.012658           6.6
76        62  74.833333   79.746835           6.2
77        50  69.833333   77.215190           5.9

[78 rows x 10 columns]

In [81]:
Intercept     0.741490
uitkering     0.018312
CV           -0.002288
werkloos      0.019899
uwv           0.043214
nieuwebaan   -0.004556
vacatures    -0.001014

SyntaxError: invalid syntax (<ipython-input-81-d4d785bea88a>, line 1)

In [122]:
nieuwebaan1 = (nieuwebaan*-0.004556)+0.741490
uitkering1 = uitkering*0.018312
CV1= CV*-0.002288
werkloos1=werkloos*0.019899
uwv1=uwv*0.043214
vacatures1=vacatures*-0.001014

In [123]:
df5= pd.concat([nieuwebaan1, uitkering1, CV1, werkloos1, uwv1, vacatures1], axis=1)

In [124]:
print(df5)

    nieuwe baan: (Nederland)  uitkering        CV  werkloos       uwv  \
0                   0.513690   1.483272 -0.208208  1.313334  2.203914
1                   0.495466   1.519896 -0.228800  1.134243  2.376770
2                   0.536470   1.556520 -0.180752  1.452627  2.463198
3                   0.500022   1.373400 -0.155584  0.895455  2.160700
4                   0.518246   1.336776 -0.155584  0.994950  2.031058
5                   0.504578   1.281840 -0.173888  1.094445  2.247128
6                   0.545582   1.190280 -0.139568  0.895455  2.203914
7                   0.454462   1.281840 -0.148720  1.014849  2.160700
8                   0.472686   1.355088 -0.192192  1.193940  2.247128
9                   0.431682   1.318464 -0.180752  1.034748  2.160700
10                  0.500022   1.355088 -0.196768  0.975051  2.203914
11                  0.504578   1.245216 -0.132704  0.935253  2.117486
12                  0.463574   1.538208 -0.192192  1.273536  2.463198
13                  0.408902   1.446648 -0.208208  1.253637  2.463198
14                  0.490910   1.483272 -0.201344  1.572021  2.419984
15                  0.486354   1.281840 -0.146432  1.293435  2.160700
16                  0.536470   1.318464 -0.146432  1.233738  2.333556
17                  0.477242   1.226904 -0.146432  1.154142  2.203914
18                  0.490910   1.245216 -0.137280  1.193940  2.117486
19                  0.463574   1.281840 -0.130416  1.054647  2.160700
20                  0.495466   1.373400 -0.183040  1.054647  2.463198
21                  0.490910   1.355088 -0.164736  1.532223  2.419984
22                  0.486354   1.428336 -0.173888  1.591920  2.549626
23                  0.490910   1.391712 -0.123552  1.432728  2.376770
24                  0.495466   1.538208 -0.180752  1.253637  2.808910
25                  0.486354   1.464960 -0.217360  1.532223  2.679268
26                  0.468130   1.538208 -0.153296  1.492425  2.722482
27                  0.541026   1.336776 -0.139568  1.452627  2.549626
28                  0.504578   1.428336 -0.137280  1.392930  2.981766
29                  0.481798   1.300152 -0.125840  1.193940  2.636054
..                       ...        ...       ...       ...       ...
48                  0.449906   1.831200 -0.189904  1.989900  3.932474
49                  0.440794   1.721328 -0.208208  1.910304  3.889260
50                  0.440794   1.703016 -0.180752  1.830708  3.846046
51                  0.477242   1.556520 -0.155584  1.651617  3.543548
52                  0.472686   1.501584 -0.148720  1.611819  3.543548
53                  0.408902   1.428336 -0.137280  1.532223  3.370692
54                  0.372454   1.428336 -0.132704  1.432728  3.457120
55                  0.436238   1.355088 -0.128128  1.333233  3.197836
56                  0.408902   1.593144 -0.178464  1.492425  3.673190
57                  0.445350   1.611456 -0.167024  1.472526  3.457120
58                  0.381566   1.629768 -0.171600  1.711314  3.413906
59                  0.436238   1.593144 -0.125840  1.392930  3.500334
60                  0.422570   1.648080 -0.185328  1.373031  3.673190
61                  0.427126   1.593144 -0.203632  1.492425  3.932474
62                  0.358786   1.574832 -0.169312  1.790910  4.191758
63                  0.427126   1.464960 -0.155584  1.512324  3.586762
64                  0.390678   1.373400 -0.139568  1.253637  3.457120
65                  0.354230   1.538208 -0.144144  1.432728  3.629976
66                  0.345118   1.446648 -0.114400  1.134243  3.629976
67                  0.422570   1.391712 -0.125840  1.114344  3.500334
68                  0.386122   1.519896 -0.176176  1.452627  3.802832
69                  0.422570   1.501584 -0.169312  1.532223  3.500334
70                  0.354230   1.464960 -0.167024  1.591920  3.543548
71                  0.372454   1.501584 -0.132704  1.492425  4.148544
72                  0.377010   1.574832 -0.187616  1.492425  4.062116
73                  0.285890   1.629768 -0.192192  1.492425  4.321400
74                  0.358786   1.574832 -0.151008  1.412829  4.062116
75                  0.322338   1.446648 -0.157872  1.353132  3.846046
76                  0.331450   1.428336 -0.141856  1.233738  4.018902
77                  0.331450   1.336776 -0.141856  0.994950  3.500334

    vacatures
0   -0.087204
1   -0.090246
2   -0.089232
3   -0.082134
4   -0.076050
5   -0.080106
6   -0.071994
7   -0.081120
8   -0.088218
9   -0.081120
10  -0.080106
11  -0.063882
12  -0.091260
13  -0.088218
14  -0.083148
15  -0.078078
16  -0.078078
17  -0.075036
18  -0.074022
19  -0.083148
20  -0.089232
21  -0.086190
22  -0.089232
23  -0.074022
24  -0.096330
25  -0.093288
26  -0.088218
27  -0.084162
28  -0.080106
29  -0.081120
..        ...
48  -0.101400
49  -0.093288
50  -0.086190
51  -0.084162
52  -0.076050
53  -0.075036
54  -0.070980
55  -0.076050
56  -0.086190
57  -0.083148
58  -0.078078
59  -0.067938
60  -0.085176
61  -0.085176
62  -0.082134
63  -0.073008
64  -0.069966
65  -0.071994
66  -0.069966
67  -0.075036
68  -0.084162
69  -0.078078
70  -0.071994
71  -0.061854
72  -0.078078
73  -0.078078
74  -0.070980
75  -0.066924
76  -0.064896
77  -0.063882

[78 rows x 6 columns]

In [125]:
df6= CV1 + uitkering1 + nieuwebaan1 + vacatures1 + werkloos1 + uwv1

In [126]:
print(df6)

0     5.218798
1     5.207329
2     5.738831
3     4.691859
4     4.649396
5     4.873997
6     4.623669
7     4.682011
8     4.988432
9     4.683722
10    4.757201
11    4.605947
12    5.455064
13    5.275959
14    5.681695
15    4.997819
16    5.197718
17    4.840734
18    4.836250
19    4.747197
20    5.114439
21    5.547279
22    5.793116
23    5.494546
24    5.819139
25    5.852157
26    5.979731
27    5.656325
28    6.090224
29    5.404984
        ...
48    7.912176
49    7.660190
50    7.553622
51    6.989181
52    6.904867
53    6.527837
54    6.486954
55    6.118217
56    6.903007
57    6.736280
58    6.886876
59    6.728868
60    6.846367
61    7.156361
62    7.664840
63    6.762580
64    6.265301
65    6.739004
66    6.371619
67    6.228084
68    6.901139
69    6.709321
70    6.715640
71    7.320449
72    7.240689
73    7.459213
74    7.186575
75    6.743368
76    6.805674
77    5.957772
dtype: float64

In [127]:
df7= pd.concat([df6, werkloosheid], axis=1)

In [128]:
print(df7)

           0  werkloosheid
0   5.218798           5.4
1   5.207329           5.5
2   5.738831           5.4
3   4.691859           5.1
4   4.649396           5.0
5   4.873997           4.9
6   4.623669           4.7
7   4.682011           4.7
8   4.988432           4.9
9   4.683722           4.9
10  4.757201           4.9
11  4.605947           4.7
12  5.455064           5.2
13  5.275959           5.3
14  5.681695           5.1
15  4.997819           4.9
16  5.197718           4.8
17  4.840734           4.6
18  4.836250           4.6
19  4.747197           4.6
20  5.114439           5.1
21  5.547279           5.2
22  5.793116           5.4
23  5.494546           5.1
24  5.819139           5.8
25  5.852157           5.8
26  5.979731           5.8
27  5.656325           5.8
28  6.090224           5.6
29  5.404984           5.5
..       ...           ...
48  7.912176           8.1
49  7.660190           8.2
50  7.553622           8.1
51  6.989181           7.9
52  6.904867           7.5
53  6.527837           7.2
54  6.486954           7.0
55  6.118217           6.8
56  6.903007           7.1
57  6.736280           7.1
58  6.886876           7.1
59  6.728868           7.0
60  6.846367           7.6
61  7.156361           7.5
62  7.664840           7.3
63  6.762580           7.1
64  6.265301           6.9
65  6.739004           6.7
66  6.371619           6.5
67  6.228084           6.4
68  6.901139           6.8
69  6.709321           6.9
70  6.715640           6.6
71  7.320449           6.4
72  7.240689           6.8
73  7.459213           6.9
74  7.186575           6.7
75  6.743368           6.6
76  6.805674           6.2
77  5.957772           5.9

[78 rows x 2 columns]

In [129]:
trace8 = Scatter(y=werkloosheid, mode= 'lines', name = 'werkloosheid')
trace9 = Scatter(y=df6, mode= 'lines', name = 'index')
data4= [trace8, trace9]
py.iplot(data4, filename='Plot4')

In [130]:
df8 = pd.read_excel("nieuwewoorden.xlsx", \
                 header = 0)

df8

    uwv2  CV2  nieuwe baan2  werkloos2  vacatures2  uitkering2
0     51   91            51         66          86          81
1     55  100            66         57          89          83
2     57   79            52         73          88          85
3     50   68            47         45          81          75
4     47   68            40         50          75          73
5     52   76            55         55          79          70
6     51   61            58         45          71          65
7     50   65            53         51          80          70
8     52   84            57         60          87          74
9     50   79            48         52          80          72
10    51   86            51         49          79          74
11    49   58            60         47          63          68
12    57   84            54         64          90          84
13    57   91            74         63          87          79
14    56   88            59         79          82          81
15    50   64            60         65          77          70
16    54   64            52         62          77          72
17    51   64            59         58          74          67
18    49   60            63         60          73          68
19    50   57            64         53          82          70
20    57   80            55         53          88          75
21    56   72            57         77          85          74
22    59   76            49         80          88          78
23    55   54            53         72          73          76
24    65   79            50         63          95          84
25    62   95            49         77          92          80
26    63   67            51         75          87          84
27    59   61            51         73          83          73
28    69   60            41         70          79          78
29    61   55            52         60          80          71
..   ...  ...           ...        ...         ...         ...
54    80   58            74         72          70          78
55    74   56            57         67          75          74
56    85   78            72         75          85          87
57    80   73            66         74          82          88
58    79   75            64         86          77          89
59    81   55            69         70          67          87
60    85   81            70         69          84          90
61    91   89            80         75          84          87
62    97   74            79         90          81          86
63    83   68            71         76          72          80
64    80   61            73         63          69          75
65    84   63            84         72          71          84
66    84   50            79         57          69          79
67    81   55            74         56          74          76
68    88   77            80         73          83          83
69    81   74            75         77          77          82
70    82   73            81         80          71          80
71    96   58            78         75          61          82
72    94   82            90         75          77          86
73   100   84           100         75          77          89
74    94   66            83         71          70          86
75    89   69            87         68          66          79
76    93   62            91         62          64          78
77    81   62            83         50          63          73
78    82   50            81         44          56          64
79    82   52            90         56          62          67
80    86   73            85         51          68          81
81    81   66            93         55          64          80
82    82   75            97         58          63          78
83    81   55            84         43          54          72

[84 rows x 6 columns]

In [131]:
df9 =  df8.drop(df8.index[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77]])
print(df9)

    uwv2  CV2  nieuwe baan2  werkloos2  vacatures2  uitkering2
78    82   50            81         44          56          64
79    82   52            90         56          62          67
80    86   73            85         51          68          81
81    81   66            93         55          64          80
82    82   75            97         58          63          78
83    81   55            84         43          54          72

In [132]:
nieuwebaan2 = df9.ix[:,2]
CV2 = df9.ix[:,1]
vacatures2 = df9.ix[:,4]
uwv2 = df9.ix[:,0]
uitkering2 = df9.ix[:,5] 
werkloos2 =  df9.ix[:,3]
print(werkloos2)

78    44
79    56
80    51
81    55
82    58
83    43
Name: werkloos2, dtype: int64

In [133]:
nieuwebaan3 = (nieuwebaan2*-0.004556)+0.741490
uitkering3 = uitkering2*0.018312
CV3= CV2*-0.002288
werkloos3=werkloos2*0.019899
uwv3=uwv2*0.043214
vacatures3=vacatures2*-0.001014

In [134]:
df10= CV3 + uitkering3 + nieuwebaan3 + vacatures3 + werkloos3 + uwv3
df11 = pd.read_excel("werkloosheidnieuw.xlsx", \
                 header = 0)
df11
werkloosheidnieuw= df11.werkloosheidnieuw
df12= pd.concat([df10, werkloosheidnieuw], axis=1)
print(df12)

           0  werkloosheidnieuw
0        NaN                5.8
1        NaN                5.4
2        NaN                5.7
3        NaN                5.7
4        NaN                5.5
5        NaN                5.1
78  5.792342                NaN
79  6.034402                NaN
80  6.332779                NaN
81  6.161617                NaN
82  6.190102                NaN
83  5.852645                NaN

In [135]:
trace10 = Scatter(x=[78,79,80,81,82,83], y=df10, mode= 'line', name = 'indexpredict')
trace11 = Scatter(x=[78,79,80,81,82,83], y=werkloosheidnieuw, mode= 'line', name = 'actual')
data5= [trace8, trace9, trace10, trace11]
py.iplot(data5, filename='Plot5')

In [95]:
1

1

In [96]:
1

1